import Image from 'next/image'
import Login from './auth/login/page'
//WORK ON THE README 
// ADUST THE FONT
//WEN A NAV LINK IS ACTIVE, IT SHOULD BE COLORED
//CONFIRM IF HAT IS A SELECT ON THE NAV
//SINCE YOURE LOGGIN IN, WILL THE NAME ON THE DASHBOARD BE DYNAMIC
//MKE THE NAVLINKS ROUTE TO PLACES
//MAKE THE SEARCH HAVE THE BACKGROUND OF SEARCH ICON
//WILL THE LOGIN PAGE BE PROTECTED 
//THE EYES ON INPUT PASSWORD
//PUT COMMENTS WERE NECESSRY
//MAKE TRANSACTION GREEN
//MAKE IT RESPONSIVE
//COLOR OF SIGFLOW OPTION

export default function Home() {
  return (
    <main className="">
      <Login />
    </main>
  )
}
